### ISSUE TITLE
space interference

### ISSUE THREAD

**Issue by CodeStuart** [yumath/bertNER#14]
![image](https://user-images.githubusercontent.com/37894906/71415206-83b6cf80-2695-11ea-872e-2d1977875a62.png)
This space seems to affect my index calculation. Do you know how to remove this interference。

**Comment by yumath** [comment]
@CodeStuart
several ways to handle this problem:
1. set MAX_SEQ_LEN bigger than your longest sentence, MAX_SEQ_LEN can not be set bigger than 512
2. split your sentences by punctuation, such as full stop, make sure your longest sentence length smaller than your MAX_SEQ_LEN-2

For every sentence to be processed by this program, it will become like this:
for example:
I like China.
O O B-LOC O
It will become like under:
[CLS] O O B-LOC O [SEP]
So it could fed into BERT
And, the space is [SEP]

**Comment by p1aCoder** [comment]
i think he means why he sets only one category ‘-1’，however，the second row in the picture  is unwanted but it appears and 7 sentences fall in this category. he wonders how to delete this unwanted category '- '. @yumath

**Comment by yumath** [comment]
@b1ackwhite Yes, I know. This program is not to classify sentences, and '-1' is not a category of sentence, but a tag of entity. Second line means 7 entities been tagging as space(actually is the [SEP], it can't display, due to it's not beginning with 'B-' or 'I-'). It's not 7 sentences, but 7 entities. To delete this unwanted tag, you have to make [SEP] not appear in the predicted tags. If you want to use BERT, you have to pad your sentence with [SEP](I have done this in codes), to make BERT know where is the boundaries of your sentence. And solution above is several ways to prevent [SEP] from appearing in the predicted tags.
